import type { ScriptReference } from '../translationPractice'

export const BENGALI_SCRIPT_REFERENCE = {
  title: 'Bengali script essentials',
  description:
    'These are practical readings for the place-name quiz. A bare consonant can carry an inherent a or o sound, and established English spellings sometimes differ from a letter-by-letter reading.',
  sections: [
    {
      title: 'Independent vowels',
      description: 'These vowel letters can stand on their own.',
      items: [
        {
          symbol: 'অ',
          romanizations: ['a', 'o'],
          note: 'The inherent vowel often sounds closer to o in spoken Bengali.',
        },
        { symbol: 'আ', romanizations: ['a'] },
        { symbol: 'ই', romanizations: ['i'] },
        { symbol: 'ঈ', romanizations: ['i'] },
        { symbol: 'উ', romanizations: ['u'] },
        { symbol: 'ঊ', romanizations: ['u'] },
        { symbol: 'ঋ', romanizations: ['ri'] },
        { symbol: 'এ', romanizations: ['e'] },
        { symbol: 'ঐ', romanizations: ['oi'] },
        { symbol: 'ও', romanizations: ['o'] },
        { symbol: 'ঔ', romanizations: ['ou'] },
      ],
    },
    {
      title: 'Dependent vowel signs',
      description:
        'The dotted circle shows where a consonant sits; the circle is not part of the Bengali spelling.',
      items: [
        { symbol: '◌া', romanizations: ['a'] },
        { symbol: '◌ি', romanizations: ['i'] },
        { symbol: '◌ী', romanizations: ['i'] },
        { symbol: '◌ু', romanizations: ['u'] },
        { symbol: '◌ূ', romanizations: ['u'] },
        { symbol: '◌ৃ', romanizations: ['ri'] },
        { symbol: '◌ে', romanizations: ['e'] },
        { symbol: '◌ৈ', romanizations: ['oi'] },
        { symbol: '◌ো', romanizations: ['o'] },
        { symbol: '◌ৌ', romanizations: ['ou'] },
      ],
    },
    {
      title: 'Consonants',
      description:
        'The guide uses practical spellings rather than distinguishing every dental and retroflex sound.',
      items: [
        { symbol: 'ক', romanizations: ['k'] },
        { symbol: 'খ', romanizations: ['kh'] },
        { symbol: 'গ', romanizations: ['g'] },
        { symbol: 'ঘ', romanizations: ['gh'] },
        { symbol: 'ঙ', romanizations: ['ng'] },
        { symbol: 'চ', romanizations: ['ch'] },
        { symbol: 'ছ', romanizations: ['chh'] },
        { symbol: 'জ', romanizations: ['j'] },
        { symbol: 'ঝ', romanizations: ['jh'] },
        { symbol: 'ঞ', romanizations: ['n', 'ny'] },
        { symbol: 'ট', romanizations: ['t'] },
        { symbol: 'ঠ', romanizations: ['th'] },
        { symbol: 'ড', romanizations: ['d'] },
        { symbol: 'ঢ', romanizations: ['dh'] },
        { symbol: 'ণ', romanizations: ['n'] },
        { symbol: 'ত', romanizations: ['t'] },
        { symbol: 'থ', romanizations: ['th'] },
        { symbol: 'দ', romanizations: ['d'] },
        { symbol: 'ধ', romanizations: ['dh'] },
        { symbol: 'ন', romanizations: ['n'] },
        { symbol: 'প', romanizations: ['p'] },
        { symbol: 'ফ', romanizations: ['ph', 'f'] },
        { symbol: 'ব', romanizations: ['b'] },
        { symbol: 'ভ', romanizations: ['bh'] },
        { symbol: 'ম', romanizations: ['m'] },
        { symbol: 'য', romanizations: ['j'] },
        { symbol: 'র', romanizations: ['r'] },
        { symbol: 'ল', romanizations: ['l'] },
        { symbol: 'শ', romanizations: ['sh'] },
        { symbol: 'ষ', romanizations: ['sh'] },
        { symbol: 'স', romanizations: ['s'] },
        { symbol: 'হ', romanizations: ['h'] },
        { symbol: 'ড়', romanizations: ['r'] },
        { symbol: 'ঢ়', romanizations: ['rh', 'r'] },
        { symbol: 'য়', romanizations: ['y'] },
      ],
    },
    {
      title: 'Other signs',
      items: [
        {
          symbol: '◌্',
          romanizations: [],
          note: 'The virama suppresses the inherent vowel and helps form a conjunct.',
        },
        { symbol: 'ং', romanizations: ['ng'], note: 'Anusvara.' },
        {
          symbol: 'ঁ',
          romanizations: ['n'],
          note: 'Chandrabindu nasalizes the preceding vowel.',
        },
        {
          symbol: 'ঃ',
          romanizations: ['h'],
          note: 'Visarga; uncommon in the place names used here.',
        },
        { symbol: 'ৎ', romanizations: ['t'], note: 'Khanda ta.' },
      ],
    },
    {
      title: 'Conjuncts found in the quiz',
      description:
        'A conjunct joins consonants with a virama. Vowel signs may attach to the complete conjunct.',
      items: [
        { symbol: 'ক্ষ', romanizations: ['ksh', 'kh'], note: 'ক + ষ' },
        { symbol: 'ক্ষ্ম', romanizations: ['kshm'], note: 'ক + ষ + ম' },
        { symbol: 'ক্স', romanizations: ['ks'], note: 'ক + স' },
        { symbol: 'গ্র', romanizations: ['gr'], note: 'গ + র' },
        { symbol: 'ঙ্গ', romanizations: ['ng', 'ngg'], note: 'ঙ + গ' },
        { symbol: 'ঞ্চ', romanizations: ['nch'], note: 'ঞ + চ' },
        { symbol: 'ঞ্জ', romanizations: ['nj'], note: 'ঞ + জ' },
        { symbol: 'ট্ট', romanizations: ['tt'], note: 'ট + ট' },
        { symbol: 'ত্র', romanizations: ['tr'], note: 'ত + র' },
        { symbol: 'দ্ধ', romanizations: ['ddh'], note: 'দ + ধ' },
        { symbol: 'ন্ত', romanizations: ['nt'], note: 'ন + ত' },
        { symbol: 'ন্দ', romanizations: ['nd'], note: 'ন + দ' },
        { symbol: 'ন্দ্র', romanizations: ['ndr'], note: 'ন + দ + র' },
        { symbol: 'ন্ধ', romanizations: ['ndh'], note: 'ন + ধ' },
        { symbol: 'ন্স', romanizations: ['nsh', 'ns'], note: 'ন + স' },
        { symbol: 'ব্র', romanizations: ['br'], note: 'ব + র' },
        { symbol: 'র্ত', romanizations: ['rt'], note: 'র + ত' },
        { symbol: 'ল্ল', romanizations: ['ll'], note: 'ল + ল' },
        { symbol: 'শ্ব', romanizations: ['shw'], note: 'শ + ব' },
        { symbol: 'শ্র', romanizations: ['shr', 'sr'], note: 'শ + র' },
        { symbol: 'ষ্ট', romanizations: ['sht', 'st'], note: 'ষ + ট' },
        { symbol: 'ষ্ণ', romanizations: ['shn'], note: 'ষ + ণ' },
        { symbol: 'স্ব', romanizations: ['sw'], note: 'স + ব' },
        { symbol: 'হ্ম', romanizations: ['hm'], note: 'হ + ম' },
      ],
    },
  ],
} satisfies ScriptReference
