import { getFeatureProperties } from '../geoJsonCodeQuiz'

export const TH_PROVINCE_ABBREVIATIONS = [
  { id: 'Amnat Charoen Province', label: 'อจ' },
  { id: 'Ang Thong Province', label: 'อท' },
  { id: 'Bueng Kan Province', label: 'บก' },
  { id: 'Buri Ram Province', label: 'บร' },
  { id: 'Chachoengsao Province', label: 'ฉช' },
  { id: 'Chai Nat Province', label: 'ชน' },
  { id: 'Chaiyaphum Province', label: 'ชย' },
  { id: 'Chanthaburi Province', label: 'จบ' },
  { id: 'Chiang Mai Province', label: 'ชม' },
  { id: 'Chiang Rai Province', label: 'ชร' },
  { id: 'Chon Buri Province', label: 'ชบ' },
  { id: 'Chumphon Province', label: 'ชพ' },
  { id: 'Kalasin', label: 'กส' },
  { id: 'Kamphaeng Phet Province', label: 'กพ' },
  { id: 'Kanchanaburi Province', label: 'กจ' },
  { id: 'Khon Kaen Province', label: 'ขก' },
  { id: 'Krabi Province', label: 'กบ' },
  { id: 'Lampang Province', label: 'ลป' },
  { id: 'Lamphun Province', label: 'ลพ' },
  { id: 'Loei Province', label: 'ลย' },
  { id: 'Lopburi Province', label: 'ลบ' },
  { id: 'Mae Hong Son Province', label: 'มส' },
  { id: 'Maha Sarakham Province', label: 'มค' },
  { id: 'Mukdahan Province', label: 'มห' },
  { id: 'Nakhon Nayok Province', label: 'นย' },
  { id: 'Nakhon Pathom Province', label: 'นฐ' },
  { id: 'Nakhon Phanom Province', label: 'นพ' },
  { id: 'Nakhon Ratchasima Province', label: 'นม' },
  { id: 'Nakhon Sawan Province', label: 'นว' },
  { id: 'Nakhon Si Thammarat Province', label: 'นศ' },
  { id: 'Nan Province', label: 'นน' },
  { id: 'Narathiwat Province', label: 'นธ' },
  { id: 'Nong Bua Lam Phu Province', label: 'นภ' },
  { id: 'Nong Khai Province', label: 'นค' },
  { id: 'Nonthaburi Province', label: 'นบ' },
  { id: 'Pathum Thani Province', label: 'ปท' },
  { id: 'Pattani Province', label: 'ปน' },
  { id: 'Phangnga Province', label: 'พง' },
  { id: 'Phatthalung Province', label: 'พท' },
  { id: 'Phayao Province', label: 'พย' },
  { id: 'Phetchabun Province', label: 'พช' },
  { id: 'Phetchaburi Province', label: 'พบ' },
  { id: 'Phichit Province', label: 'พจ' },
  { id: 'Phitsanulok Province', label: 'พล' },
  { id: 'Phra Nakhon Si Ayutthaya Province', label: 'อย' },
  { id: 'Phrae Province', label: 'พร' },
  { id: 'Phuket Province', label: 'ภก' },
  { id: 'Prachin Buri Province', label: 'ปจ' },
  { id: 'Prachuap Khiri Khan Province', label: 'ปข' },
  { id: 'Ranong Province', label: 'รน' },
  { id: 'Ratchaburi Province', label: 'รบ' },
  { id: 'Rayong Province', label: 'รย' },
  { id: 'Roi Et Province', label: 'รอ' },
  { id: 'Sa Kaeo Province', label: 'สก' },
  { id: 'Sakon Nakhon Province', label: 'สน' },
  { id: 'Samut Prakan Province', label: 'สป' },
  { id: 'Samut Sakhon Province', label: 'สค' },
  { id: 'Samut Songkhram Province', label: 'สส' },
  { id: 'Saraburi Province', label: 'สบ' },
  { id: 'Satun Province', label: 'สต' },
  { id: 'Si Sa Ket Province', label: 'ศก' },
  { id: 'Sing Buri Province', label: 'สห' },
  { id: 'Songkhla Province', label: 'สข' },
  { id: 'Sukhothai Province', label: 'สท' },
  { id: 'Suphan Buri Province', label: 'สพ' },
  { id: 'Surat Thani Province', label: 'สฎ' },
  { id: 'Surin Province', label: 'สร' },
  { id: 'Tak Province', label: 'ตก' },
  { id: 'Trang Province', label: 'ตง' },
  { id: 'Trat Province', label: 'ตร' },
  { id: 'Ubon Ratchathani Province', label: 'อบ' },
  { id: 'Udon Thani Province', label: 'อด' },
  { id: 'Uthai Thani Province', label: 'อน' },
  { id: 'Uttaradit Province', label: 'อต' },
  { id: 'Yala Province', label: 'ยล' },
  { id: 'Yasothon Province', label: 'ยส' },
]

const TH_PROVINCE_ABBREVIATION_IDS = new Set<string>(
  TH_PROVINCE_ABBREVIATIONS.map((province) => province.id)
)

export function getThailandProvinceAbbreviationIds(feature: unknown) {
  const rawProvince = getFeatureProperties(feature)?.shapeName
  if (typeof rawProvince !== 'string') return []

  const province = rawProvince.trim()
  return TH_PROVINCE_ABBREVIATION_IDS.has(province) ? [province] : []
}
