export type Regency = { province: string; name: string }
export type ProvinceData = { province: string; regencies: string[] }
export const ID_MAP: Record<string, string[]> = {
  "Aceh": [
    "Aceh Jaya",
    "Simeulue",
    "Aceh Singkil",
    "Aceh Selatan",
    "Aceh Tenggara",
    "Aceh Timur",
    "Aceh Tengah",
    "Aceh Barat",
    "Aceh Besar",
    "Pidie",
    "Bireuen",
    "Aceh Utara",
    "Aceh Barat Daya",
    "Gayo Lues",
    "Aceh Tamiang",
    "Nagan Raya",
    "Bener Meriah",
    "Pidie Jaya",
    "Banda Aceh",
    "Sabang",
    "Langsa",
    "Lhokseumawe",
    "Subulussalam"
  ],
  "North Sumatra": [
    "Padang Lawas",
    "Padang Lawas Utara",
    "Nias",
    "Mandailing Natal",
    "Tapanuli Selatan",
    "Tapanuli Tengah",
    "Tapanuli Utara",
    "Toba",
    "Labuhan Batu",
    "Asahan",
    "Simalungun",
    "Dairi",
    "Karo",
    "Deli Serdang",
    "Langkat",
    "Nias Selatan",
    "Humbang Hasundutan",
    "Pakpak Bharat",
    "Samosir",
    "Serdang Bedagal",
    "Batubara",
    "Labuhanbatu Selatan",
    "Labuhanbatu",
    "Nias Utara",
    "Nias Barat",
    "Sibolga",
    "Tanjungbalai",
    "Pematangsiantar",
    "Tebing Tinggi",
    "Medan",
    "Binjai",
    "Padang Sidempuan",
    "Gunungsitoli"
  ],
  "West Sumatra": [
    "Kepulauan Mentawai",
    "Pesisir Selatan",
    "Solok",
    "Sijunjung",
    "Tanah Datar",
    "Padang Pariaman",
    "Agam",
    "Lima Puluh Kota",
    "Pasaman",
    "Solok Selatan",
    "Dharmasraya",
    "Pasaman Barat",
    "Padang",
    "Solok (kota)",
    "Sawahlunto",
    "Padang Panjang",
    "Bukittinggi",
    "Payakumbuh",
    "Pariaman"
  ],
  "Jambi": [
    "Kerinci",
    "Merangin",
    "Sarolangun",
    "Batang Hari",
    "Muaro Jambi",
    "Tanjung Jabung Timur",
    "Tanjung Jabung Barat",
    "Tebo",
    "Bungo",
    "Jambi",
    "Sungai Penuh"
  ],
  "Riau": [
    "Rokan Hilir",
    "Rokan Hulu",
    "Kuantan Singingi",
    "Indragiri Hulu",
    "Indragiri Hilir",
    "Pelalawan",
    "Siak",
    "Kampar",
    "Bengkalis",
    "Kepulauan Meranti",
    "Pekanbaru",
    "Dumai"
  ],
  "Bengkulu": [
    "Seluma",
    "Bengkulu Selatan",
    "Rejang Lebong",
    "Bengkulu Utara",
    "Kaur",
    "Mukomuko",
    "Lebong",
    "Kepahiang",
    "Bengkulu Tengah",
    "Bengkulu"
  ],
  "South Sumatra": [
    "Penukal Abab Lematang Ilir",
    "Musi Rawas Utara",
    "Ogan Komering Ulu",
    "Ogan Komering Ilir",
    "Muara Enim",
    "Lahat",
    "Musi Rawas",
    "Musi Banyuasin",
    "Banyuasin",
    "Ogan Komering Ulu Selatan",
    "Ogan Komering Ulu Timur",
    "Ogan Ilir",
    "Empat Lawang",
    "Palembang",
    "Prabumulih",
    "Pagar Alam",
    "Lubuklinggau"
  ],
  "Lampung": [
    "Lampung Barat",
    "Pesisir Barat",
    "Tulang Bawang Barat",
    "Tanggamus",
    "Lampung Selatan",
    "Lampung Timur",
    "Lampung Tengah",
    "Lampung Utara",
    "Way Kanan",
    "Tulangbawang",
    "Pesawaran",
    "Pringsewu",
    "Mesuji",
    "Bandar Lampung",
    "Metro"
  ],
  "Bangka Belitung Islands": [
    "Bangka",
    "Belitung",
    "Bangka Barat",
    "Bangka Tengah",
    "Bangka Selatan",
    "Belitung Timur",
    "Pangkalpinang"
  ],
  "Riau Islands": [
    "Karimun",
    "Bintan",
    "Natuna",
    "Lingga",
    "Anambas Islands",
    "Batam",
    "Tanjung Pinang"
  ],
  "Jakarta": [
    "Jakarta Selatan",
    "Jakarta Pusat",
    "Jakarta Barat",
    "Jakarta Utara"
  ],
  "Banten": [
    "Pandeglang",
    "Lebak",
    "Tangerang",
    "Serang",
    "Tangerang (kota)",
    "Cilegon",
    "Serang (kota)",
    "Tangerang Selatan"
  ],
  "West Java": [
    "Pangandaran",
    "Bogor",
    "Sukabumi",
    "Cianjur",
    "Bandung",
    "Garut",
    "Tasikmalaya",
    "Ciamis",
    "Kuningan",
    "Cirebon",
    "Majalengka",
    "Sumedang",
    "Indramayu",
    "Subang",
    "Purwakarta",
    "Karawang",
    "Bekasi",
    "Bandung Barat",
    "Bogor (kota)",
    "Sukabumi (kota)",
    "Bandung (kota)",
    "Cirebon (kota)",
    "Bekasi (kota)",
    "Depok",
    "Cimahi",
    "Tasikmalaya (kota)",
    "Banjar (kota)"
  ],
  "Central Java": [
    "Cilacap",
    "Banyumas",
    "Purbalingga",
    "Banjarnegara",
    "Kebumen",
    "Purworejo",
    "Wonosobo",
    "Magelang",
    "Boyolali",
    "Klaten",
    "Sukoharjo",
    "Wonogiri",
    "Karanganyar",
    "Sragen",
    "Grobogan",
    "Blora",
    "Pembang",
    "Pati",
    "Kudus",
    "Jepara",
    "Demak",
    "Semarang",
    "Temanggung",
    "Kendal",
    "Batang",
    "Pekalongan",
    "Pemalang",
    "Tegal",
    "Brebes",
    "Magelang (kota)",
    "Surwakarta (kota)",
    "Salatiga",
    "Semarang (kota)",
    "Pekalongan (kota)",
    "Tegal (kota)"
  ],
  "Yogyakarta": [
    "Kulonprogo",
    "Bantul",
    "Gunungkidul",
    "Sleman",
    "Yogyakarta"
  ],
  "East Java": [
    "Pacitan",
    "Ponorogo",
    "Trenggalek",
    "Tulungagung",
    "Blitar",
    "Kediri",
    "Malang",
    "Lumajang",
    "Jember",
    "Banyuwangi",
    "Bondowoso",
    "Situbondo",
    "Pasuruan",
    "Sidoarjo",
    "Mojokerto",
    "Jombang",
    "Nganjuk",
    "Madiun",
    "Magetan",
    "Bojonegoro",
    "Tuban",
    "Lamongan",
    "Gresik",
    "Bangkalan",
    "Sampang",
    "Pamekasan",
    "Sumenep",
    "Kediri (kota)",
    "Blitar (kota)",
    "Malang (kota)",
    "Probolinggo (kota)",
    "Pasuruan (kota)",
    "Mojokerto (kota)",
    "Madiun (kota)",
    "Surabaya",
    "Batu"
  ],
  "Bali": [
    "Jembrana",
    "Tabanan",
    "Badung",
    "Gianyar",
    "Klungkung",
    "Bangli",
    "Karangasem",
    "Buleleng",
    "Denpasar"
  ],
  "West Nusa Tenggara": [
    "Lombok Barat",
    "Lombok Tengah",
    "Lombok Timur",
    "Sumbawa",
    "Dompu",
    "Bima",
    "Sumbawa Barat",
    "Lombok Utara",
    "Mataram",
    "Bima (kota)"
  ],
  "East Nusa Tenggara": [
    "Belu",
    "Sumba Barat",
    "Sumba Timur",
    "Kupang",
    "Timor Tengah Selatan",
    "Timor Tengah Utara",
    "Malaka",
    "Alor",
    "Lembata",
    "Flores Timur",
    "Sikka",
    "Ende",
    "Ngada",
    "Manggarai",
    "Rote Ndao",
    "Manggarai Barat",
    "Sumba Tengah",
    "Sumba Barat Daya",
    "Nagekeo",
    "Manggarai Timur",
    "Sabu Raijua"
  ],
  "West Kalimantan": [
    "Sambas",
    "Bengkayang",
    "Landak",
    "Mempawah",
    "Sanggau",
    "Ketapang",
    "Sintang",
    "Kapuas Hulu",
    "Sekadau",
    "Melawi",
    "Kayong Utara",
    "Kuburaya",
    "Pontianak",
    "Sinkawang"
  ],
  "Central Kalimantan": [
    "Kotawaringin Barat",
    "Kotawaringin Timur",
    "Kapuas",
    "Barito Selatan",
    "Barito Utara",
    "Sukamara",
    "Lamandau",
    "Seruyan",
    "Katingan",
    "Pulang Pisau",
    "Gunung Mas",
    "Barito Timur",
    "Murung Raya",
    "Palang Raya"
  ],
  "South Kalimantan": [
    "Tanah Laut",
    "Kotabaru",
    "Banjar",
    "Barito Kuala",
    "Tapin",
    "Hulu Sungai Selatan",
    "Hulu Sungai Tengah",
    "Hulu Sungai Utara",
    "Tabalong",
    "Tanah Bumbu",
    "Balangan",
    "Banjarmasin",
    "Banjarbaru"
  ],
  "East Kalimantan": [
    "Kutai Barat",
    "Kutai Kartanegara",
    "Paser",
    "Mahakam Ulu",
    "Kutai Timur",
    "Berau",
    "Balikpapan",
    "Samarinda",
    "Penajam Paser Utara",
    "Bontang"
  ],
  "North Kalimantan": [
    "Malinau",
    "Bulungan",
    "Nunukan",
    "Tana Tidung",
    "Tarakan"
  ],
  "North Sulawesi": [
    "Bolaang Mongondow",
    "Minahasa",
    "Kepulauan Sangihe",
    "Kepulauan Talaud",
    "Minahasa Selatan",
    "Minahasa Utara",
    "Bolaang Mongondow Utara",
    "Sitaro Islands",
    "Minahasa Tenggara",
    "Bolaang Mongondow Selatan",
    "Bolaang Mongondow Timur",
    "Manado",
    "Bitung",
    "Tomohon",
    "Kotamobagu"
  ],
  "Central Sulawesi": [
    "Banggai",
    "Banggai Kepulauan",
    "Poso",
    "Donggala",
    "Toli-toli",
    "Buol",
    "Parigi Moutong",
    "Tojo Una-una",
    "Sigi",
    "Palu",
    "Banggai Laut",
    "Morowali Utara",
    "Morowali"
  ],
  "South Sulawesi": [
    "Kepulauan Selayar",
    "Bulukumba",
    "Bantaeng",
    "Jeneponto",
    "Takalar",
    "Gowa",
    "Sinjai",
    "Maros",
    "Pangkajene Kepulauan",
    "Barru",
    "Bone",
    "Soppeng",
    "Wajo",
    "Sidenreng Rappang",
    "Pinrang",
    "Enrekang",
    "Luwu",
    "Tana Toraja",
    "Luwu Utara",
    "Luwu Timur",
    "Toraja Utara",
    "Makassar",
    "Pare-pare",
    "Palopo"
  ],
  "Southeast Sulawesi": [
    "Muna Barat",
    "Kolaka Timur",
    "Muna",
    "Konawe Kepulauan",
    "Konawe",
    "Kolaka",
    "Konawe Selatan",
    "Bombana",
    "Wakatobi",
    "Kolaka Utara",
    "Buton Utara",
    "Konawe Utara",
    "Kendari",
    "Bau-bau",
    "Buton Tengah",
    "Buton Selatan",
    "Buton"
  ],
  "Gorontalo": [
    "Boalemo",
    "Gorontalo",
    "Pohuwato",
    "Bone Bolango",
    "Gorontalo Utara",
    "Gorontalo (kota)"
  ],
  "West Sulawesi": [
    "Mamuju Tengah",
    "Majene",
    "Polewali Mandar",
    "Mamasa",
    "Mamuju",
    "Pasangkayu"
  ],
  "Maluku": [
    "Tanimbar Islands",
    "Maluku Tenggara",
    "Maluku Tengah",
    "Buru",
    "Aru Islands",
    "Seram Bagian Barat",
    "Seram Bagian Timur",
    "Maluku Barat Daya",
    "Buru Selatan",
    "Ambon",
    "Tual"
  ],
  "North Maluku": [
    "Pulau Taliabu",
    "Halmahera Utara",
    "Halmahera Barat",
    "Halmahera Tengah",
    "Kepulauan Sula",
    "Halmahera Selatan",
    "Halmahera Timur",
    "Pulau Morotai",
    "Ternate",
    "Tidore Kepulauan"
  ],
  "West Papua": [
    "Manokwari Selatan",
    "Pegunungan Arfak",
    "Fakfak",
    "Kaimana",
    "Teluk Wondama",
    "Teluk Bintuni",
    "Manokwari"
  ],
  "Southwest Papua": [
    "Sorong Selatan",
    "Sorong",
    "Raja Ampat",
    "Tambrauw",
    "Maybrat",
    "Sorong (kota)"
  ],
  "Papua": [
    "Jayapura",
    "Jayapura (kota)",
    "Kepulauan Yapen",
    "Biak Numfor",
    "Sarmi",
    "Keerom",
    "Waropen",
    "Supiori",
    "Mamberamo Raya"
  ],
  "Highland Papua": [
    "Jayawijaya",
    "Yahukimo",
    "Pegunungan Bintang",
    "Tolikara",
    "Nduga",
    "Lanny Jaya",
    "Mamberamo Tengah",
    "Yalimo"
  ],
  "Central Papua": [
    "Nabire",
    "Paniai",
    "Puncak Jaya",
    "Mimika",
    "Puncak",
    "Dogiyai",
    "Intan Jaya",
    "Deiyai"
  ],
  "South Papua": [
    "Merauke",
    "Boven Digoel",
    "Mappi",
    "Asmat"
  ]
}
