import type { ScriptReference } from '../translationPractice'

export const HINDI_SCRIPT_REFERENCE = {
  title: 'Hindi script essentials',
  description:
    'Hindi uses Devanagari. These are practical readings for district names; established English spellings may omit inherent vowels or use a conventional spelling rather than a letter-by-letter transliteration.',
  sections: [
    {
      title: 'Independent vowels',
      description: 'These vowel letters can stand on their own.',
      items: [
        { symbol: 'अ', romanizations: ['a'] },
        { symbol: 'आ', romanizations: ['aa', 'a'] },
        { symbol: 'इ', romanizations: ['i'] },
        { symbol: 'ई', romanizations: ['ee', 'i'] },
        { symbol: 'उ', romanizations: ['u'] },
        { symbol: 'ऊ', romanizations: ['oo', 'u'] },
        { symbol: 'ऋ', romanizations: ['ri'] },
        { symbol: 'ए', romanizations: ['e'] },
        { symbol: 'ऐ', romanizations: ['ai'] },
        { symbol: 'ओ', romanizations: ['o'] },
        { symbol: 'औ', romanizations: ['au'] },
      ],
    },
    {
      title: 'Dependent vowel signs',
      description:
        'The dotted circle marks the consonant position and is not part of the spelling. A consonant without a sign normally carries an inherent a sound, although Hindi often drops it at the end of a syllable or word.',
      items: [
        { symbol: '◌ा', romanizations: ['aa', 'a'] },
        {
          symbol: '◌ि',
          romanizations: ['i'],
          note: 'Written before its consonant but pronounced after it.',
        },
        { symbol: '◌ी', romanizations: ['ee', 'i'] },
        { symbol: '◌ु', romanizations: ['u'] },
        { symbol: '◌ू', romanizations: ['oo', 'u'] },
        { symbol: '◌ृ', romanizations: ['ri'] },
        { symbol: '◌े', romanizations: ['e'] },
        { symbol: '◌ै', romanizations: ['ai'] },
        { symbol: '◌ो', romanizations: ['o'] },
        { symbol: '◌ौ', romanizations: ['au'] },
      ],
    },
    {
      title: 'Consonants',
      description:
        'The guide uses practical Latin spellings and groups dental and retroflex sounds under familiar English letters.',
      items: [
        { symbol: 'क', romanizations: ['k'] },
        { symbol: 'ख', romanizations: ['kh'] },
        { symbol: 'ग', romanizations: ['g'] },
        { symbol: 'घ', romanizations: ['gh'] },
        { symbol: 'ङ', romanizations: ['ng'] },
        { symbol: 'च', romanizations: ['ch'] },
        { symbol: 'छ', romanizations: ['chh'] },
        { symbol: 'ज', romanizations: ['j'] },
        { symbol: 'झ', romanizations: ['jh'] },
        { symbol: 'ञ', romanizations: ['ny', 'n'] },
        { symbol: 'ट', romanizations: ['t'] },
        { symbol: 'ठ', romanizations: ['th'] },
        { symbol: 'ड', romanizations: ['d'] },
        { symbol: 'ढ', romanizations: ['dh'] },
        { symbol: 'ण', romanizations: ['n'] },
        { symbol: 'त', romanizations: ['t'] },
        { symbol: 'थ', romanizations: ['th'] },
        { symbol: 'द', romanizations: ['d'] },
        { symbol: 'ध', romanizations: ['dh'] },
        { symbol: 'न', romanizations: ['n'] },
        { symbol: 'प', romanizations: ['p'] },
        { symbol: 'फ', romanizations: ['ph', 'f'] },
        { symbol: 'ब', romanizations: ['b'] },
        { symbol: 'भ', romanizations: ['bh'] },
        { symbol: 'म', romanizations: ['m'] },
        { symbol: 'य', romanizations: ['y'] },
        { symbol: 'र', romanizations: ['r'] },
        { symbol: 'ल', romanizations: ['l'] },
        { symbol: 'व', romanizations: ['v', 'w'] },
        { symbol: 'श', romanizations: ['sh'] },
        { symbol: 'ष', romanizations: ['sh'] },
        { symbol: 'स', romanizations: ['s'] },
        { symbol: 'ह', romanizations: ['h'] },
      ],
    },
    {
      title: 'Modified consonants and other signs',
      items: [
        {
          symbol: '◌़',
          romanizations: [],
          note: 'Nukta: a dot that modifies a consonant, often for sounds borrowed from Persian or English.',
        },
        { symbol: 'क़', romanizations: ['q', 'k'] },
        { symbol: 'ख़', romanizations: ['kh'] },
        { symbol: 'ग़', romanizations: ['gh', 'g'] },
        { symbol: 'ज़', romanizations: ['z'] },
        { symbol: 'ड़', romanizations: ['r', 'd'] },
        { symbol: 'ढ़', romanizations: ['rh', 'dh'] },
        { symbol: 'फ़', romanizations: ['f'] },
        {
          symbol: '◌्',
          romanizations: [],
          note: 'Halant/virama: removes the inherent vowel and joins consonants.',
        },
        { symbol: 'ं', romanizations: ['n', 'm'], note: 'Anusvara.' },
        {
          symbol: 'ँ',
          romanizations: ['n'],
          note: 'Chandrabindu nasalizes the preceding vowel.',
        },
        { symbol: 'ः', romanizations: ['h'], note: 'Visarga.' },
      ],
    },
    {
      title: 'Common joined forms',
      description:
        'A halant joins consonants into a cluster. Their appearance may change, but the consonants remain readable as a unit.',
      items: [
        { symbol: 'क्ष', romanizations: ['ksh'], note: 'क + ष' },
        { symbol: 'त्र', romanizations: ['tr'], note: 'त + र' },
        { symbol: 'ज्ञ', romanizations: ['gy', 'jny'], note: 'ज + ञ' },
        { symbol: 'श्र', romanizations: ['shr'], note: 'श + र' },
        { symbol: 'क्र', romanizations: ['kr'], note: 'क + र' },
        { symbol: 'ग्र', romanizations: ['gr'], note: 'ग + र' },
        { symbol: 'प्र', romanizations: ['pr'], note: 'प + र' },
        { symbol: 'ब्र', romanizations: ['br'], note: 'ब + र' },
        { symbol: 'द्र', romanizations: ['dr'], note: 'द + र' },
        { symbol: 'स्त', romanizations: ['st'], note: 'स + त' },
        { symbol: 'न्द', romanizations: ['nd'], note: 'न + द' },
        { symbol: 'न्ध', romanizations: ['ndh'], note: 'न + ध' },
        { symbol: 'च्छ', romanizations: ['chch'], note: 'च + छ' },
      ],
    },
  ],
} satisfies ScriptReference
