import { getFeatureProperties } from '../geoJsonCodeQuiz'

const FRANCE_DEPARTMENT_NAMES = [
  'Ain',
  'Aisne',
  'Allier',
  'Alpes-Maritimes',
  'Alpes-de-Haute-Provence',
  'Ardennes',
  'Ardèche',
  'Ariège',
  'Aube',
  'Aude',
  'Aveyron',
  'Bas-Rhin',
  'Bouches-du-Rhône',
  'Calvados',
  'Cantal',
  'Charente',
  'Charente-Maritime',
  'Cher',
  'Corrèze',
  'Corse-du-Sud',
  'Creuse',
  "Côte-d'Or",
  "Côtes-d'Armor",
  'Deux-Sèvres',
  'Dordogne',
  'Doubs',
  'Drôme',
  'Essonne',
  'Eure',
  'Eure-et-Loir',
  'Finistère',
  'Gard',
  'Gers',
  'Gironde',
  'Haut-Rhin',
  'Haute-Corse',
  'Haute-Garonne',
  'Haute-Loire',
  'Haute-Marne',
  'Haute-Savoie',
  'Haute-Saône',
  'Haute-Vienne',
  'Hautes-Alpes',
  'Hautes-Pyrénées',
  'Hauts-de-Seine',
  'Hérault',
  'Ille-et-Vilaine',
  'Indre',
  'Indre-et-Loire',
  'Isère',
  'Jura',
  'Landes',
  'Loir-et-Cher',
  'Loire',
  'Loire-Atlantique',
  'Loiret',
  'Lot',
  'Lot-et-Garonne',
  'Lozère',
  'Maine-et-Loire',
  'Manche',
  'Marne',
  'Mayenne',
  'Meurthe-et-Moselle',
  'Meuse',
  'Morbihan',
  'Moselle',
  'Nièvre',
  'Nord',
  'Oise',
  'Orne',
  'Paris',
  'Pas-de-Calais',
  'Puy-de-Dôme',
  'Pyrénées-Atlantiques',
  'Pyrénées-Orientales',
  'Rhône',
  'Sarthe',
  'Savoie',
  'Saône-et-Loire',
  'Seine-Maritime',
  'Seine-Saint-Denis',
  'Seine-et-Marne',
  'Somme',
  'Tarn',
  'Tarn-et-Garonne',
  'Territoire de Belfort',
  "Val-d'Oise",
  'Val-de-Marne',
  'Var',
  'Vaucluse',
  'Vendée',
  'Vienne',
  'Vosges',
  'Yonne',
  'Yvelines',
]

export const FR_DEPARTMENTS = FRANCE_DEPARTMENT_NAMES.map((department) => ({
  id: department,
  label: department,
}))

const FR_DEPARTMENT_IDS = new Set(
  FR_DEPARTMENTS.map((department) => department.id)
)

export function getFranceDepartmentIds(feature: unknown) {
  const department = getFeatureProperties(feature)?.nom
  if (typeof department !== 'string') return []

  const normalizedDepartment = department.trim()
  return FR_DEPARTMENT_IDS.has(normalizedDepartment)
    ? [normalizedDepartment]
    : []
}
