"""Spatially assign Turkey district polygons to provinces and build quiz data.

Run from the repository root. This development script requires Shapely.
"""

import json
import os
import re
from collections import defaultdict
from pathlib import Path

from shapely.geometry import shape


PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent
DISTRICT_GEOJSON_PATH = PROJECT_DIRECTORY / "public/trdistrict.geojson"
PROVINCE_GEOJSON_PATH = PROJECT_DIRECTORY / "public/trprovince.geojson"
PROVINCE_DATA_PATH = PROJECT_DIRECTORY / "src/utils/tr/provinceData.ts"
GENERATED_DATA_PATH = PROJECT_DIRECTORY / "src/utils/tr/districts.generated.ts"


def read_json(path: Path):
    with path.open(encoding="utf-8") as source:
        return json.load(source)


def write_text_safely(path: Path, value: str):
    temporary_path = path.with_suffix(f"{path.suffix}.tmp")
    temporary_path.write_text(value, encoding="utf-8")
    os.replace(temporary_path, path)


def get_province_names_by_code():
    source = PROVINCE_DATA_PATH.read_text(encoding="utf-8")
    names_by_code = dict(
        re.findall(r"\['(\d{3})', '([^']+)'\]", source)
    )
    names_by_code["216"] = "İstanbul"
    if len(set(names_by_code.values())) != 81:
        raise RuntimeError("Expected all 81 Turkish provinces in provinceData.ts.")
    return names_by_code


def main():
    district_data = read_json(DISTRICT_GEOJSON_PATH)
    province_data = read_json(PROVINCE_GEOJSON_PATH)
    province_names_by_code = get_province_names_by_code()
    province_geometries = [
        (str(feature["properties"]["code"]), shape(feature["geometry"]))
        for feature in province_data["features"]
    ]
    districts_by_province = defaultdict(set)

    for feature in district_data["features"]:
        district_geometry = shape(feature["geometry"])
        representative_point = district_geometry.representative_point()
        matches = [
            code
            for code, province_geometry in province_geometries
            if province_geometry.covers(representative_point)
        ]
        if len(matches) != 1:
            overlaps = sorted(
                (
                    district_geometry.intersection(province_geometry).area,
                    code,
                )
                for code, province_geometry in province_geometries
            )
            if not overlaps or overlaps[-1][0] <= 0:
                district = feature["properties"].get("district", "Unknown")
                raise RuntimeError(f"Unable to assign {district} to a province.")
            matches = [overlaps[-1][1]]

        province = province_names_by_code.get(matches[0])
        district = feature["properties"].get("district")
        if not province or not isinstance(district, str) or not district:
            raise RuntimeError("A district has invalid properties.")

        feature["properties"]["province"] = province
        districts_by_province[province].add(district)

    district_count = sum(len(districts) for districts in districts_by_province.values())
    if len(districts_by_province) != 81 or district_count != 973:
        raise RuntimeError(
            f"Expected 973 districts across 81 provinces, got {district_count} "
            f"across {len(districts_by_province)} provinces."
        )

    geojson_text = json.dumps(
        district_data,
        ensure_ascii=False,
        separators=(",", ":"),
    )
    write_text_safely(DISTRICT_GEOJSON_PATH, geojson_text)

    generated_data = {
        province: sorted(districts)
        for province, districts in sorted(districts_by_province.items())
    }
    generated_text = (
        "// Generated by scripts/generateTurkeyDistrictData.py.\n"
        "export const TURKEY_DISTRICTS_BY_PROVINCE = "
        f"{json.dumps(generated_data, ensure_ascii=False, indent=2)} as const\n"
    )
    write_text_safely(GENERATED_DATA_PATH, generated_text)

    print(f"Generated {district_count} Turkey districts across 81 provinces.")


if __name__ == "__main__":
    main()
