"""Spatially assign Germany districts to Regierungsbezirke and states.

Run from the repository root. This development script requires Shapely.
"""

import json
import os
from collections import defaultdict
from pathlib import Path

from shapely import make_valid
from shapely.geometry import shape


PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent
DISTRICT_GEOJSON_PATH = PROJECT_DIRECTORY / "public/dedistrict.geojson"
REGION_GEOJSON_PATH = PROJECT_DIRECTORY / "public/deregierungsbezirk.geojson"
STATE_GEOJSON_PATH = PROJECT_DIRECTORY / "public/destate.geojson"
GENERATED_DATA_PATH = PROJECT_DIRECTORY / "src/utils/de/districts.generated.ts"


def read_json(path: Path):
    with path.open(encoding="utf-8") as source:
        return json.load(source)


def write_text_safely(path: Path, value: str):
    temporary_path = path.with_suffix(f"{path.suffix}.tmp")
    temporary_path.write_text(value, encoding="utf-8")
    os.replace(temporary_path, path)


def valid_geometry(feature):
    return make_valid(shape(feature["geometry"]))


def assign_area(geometries, areas, label: str):
    largest_geometry = max(geometries, key=lambda geometry: geometry.area)
    representative_point = largest_geometry.representative_point()
    matches = [
        name
        for name, area_geometry in areas
        if area_geometry.covers(representative_point)
    ]
    if len(matches) == 1:
        return matches[0]

    overlaps = sorted(
        (
            sum(
                geometry.intersection(area_geometry).area
                for geometry in geometries
            ),
            name,
        )
        for name, area_geometry in areas
    )
    if not overlaps or overlaps[-1][0] <= 0:
        raise RuntimeError(f"Unable to spatially assign {label}.")
    return overlaps[-1][1]


def main():
    district_data = read_json(DISTRICT_GEOJSON_PATH)
    region_data = read_json(REGION_GEOJSON_PATH)
    state_data = read_json(STATE_GEOJSON_PATH)

    regions = [
        (feature["properties"]["shapeName"], valid_geometry(feature))
        for feature in region_data["features"]
    ]
    states = [
        (feature["properties"]["state"], valid_geometry(feature))
        for feature in state_data["features"]
    ]

    state_by_region = {
        region: assign_area([geometry], states, region)
        for region, geometry in regions
    }
    regions_by_state = defaultdict(set)
    for region, state in state_by_region.items():
        regions_by_state[state].add(region)

    feature_indices_by_district = defaultdict(list)
    geometries_by_district = defaultdict(list)
    for index, feature in enumerate(district_data["features"]):
        district = feature["properties"].get("district")
        if not isinstance(district, str) or not district:
            raise RuntimeError("A district has an invalid name.")
        feature_indices_by_district[district].append(index)
        geometries_by_district[district].append(valid_geometry(feature))

    districts_by_region = defaultdict(set)
    for district, geometries in geometries_by_district.items():
        region = assign_area(geometries, regions, district)
        state = assign_area(geometries, states, district)
        if state_by_region[region] != state:
            raise RuntimeError(
                f"The assignments for {district} disagree: {region} / {state}."
            )

        districts_by_region[region].add(district)
        for index in feature_indices_by_district[district]:
            properties = district_data["features"][index]["properties"]
            properties["regierungsbezirk"] = region
            properties["state"] = state

    district_count = sum(
        len(districts) for districts in districts_by_region.values()
    )
    if district_count != 401 or len(districts_by_region) != 38:
        raise RuntimeError(
            f"Expected 401 districts across 38 regions, got {district_count} "
            f"across {len(districts_by_region)} regions."
        )
    if len(regions_by_state) != 16:
        raise RuntimeError(
            f"Expected regions in 16 states, got {len(regions_by_state)}."
        )

    write_text_safely(
        DISTRICT_GEOJSON_PATH,
        json.dumps(district_data, ensure_ascii=False, separators=(",", ":")),
    )

    generated_districts = {
        region: sorted(districts)
        for region, districts in sorted(districts_by_region.items())
    }
    generated_regions = {
        state: sorted(regions)
        for state, regions in sorted(regions_by_state.items())
    }
    generated_text = (
        "// Generated by scripts/generateGermanyDistrictData.py.\n"
        "export const GERMANY_DISTRICTS_BY_REGIERUNGSBEZIRK = "
        f"{json.dumps(generated_districts, ensure_ascii=False, indent=2)} as const\n\n"
        "export const GERMANY_REGIERUNGSBEZIRKE_BY_STATE = "
        f"{json.dumps(generated_regions, ensure_ascii=False, indent=2)} as const\n"
    )
    write_text_safely(GENERATED_DATA_PATH, generated_text)

    print(
        f"Generated {district_count} Germany districts across 38 selector "
        "regions and 16 states."
    )


if __name__ == "__main__":
    main()
