import { getFeatureProperties } from '../geoJsonCodeQuiz'

export const ID_MAP: Record<string, string[]> = {
  Aceh: [
    'Aceh Barat',
    'Aceh Barat Daya',
    'Aceh Besar',
    'Aceh Jaya',
    'Aceh Selatan',
    'Aceh Singkil',
    'Aceh Tamiang',
    'Aceh Tengah',
    'Aceh Tenggara',
    'Aceh Timur',
    'Aceh Utara',
    'Bener Meriah',
    'Bireuen',
    'Gayo Lues',
    'Kota Banda Aceh',
    'Kota Langsa',
    'Kota Lhokseumawe',
    'Kota Sabang',
    'Kota Subulussalam',
    'Nagan Raya',
    'Pidie',
    'Pidie Jaya',
    'Simeulue',
  ],
  'North Sumatra': [
    'Asahan',
    'Batu Bara',
    'Dairi',
    'Deli Serdang',
    'Humbang Hasundutan',
    'Karo',
    'Kota Binjai',
    'Kota Gunungsitoli',
    'Kota Medan',
    'Kota Padang Sidempuan',
    'Kota Pematangsiantar',
    'Kota Sibolga',
    'Kota Tanjung Balai',
    'Kota Tebing Tinggi',
    'Labuhanbatu',
    'Labuhanbatu Selatan',
    'Labuhanbatu Utara',
    'Langkat',
    'Mandailing Natal',
    'Nias',
    'Nias Barat',
    'Nias Selatan',
    'Nias Utara',
    'Padang Lawas',
    'Padang Lawas Utara',
    'Pakpak Bharat',
    'Samosir',
    'Serdang Bedagai',
    'Simalungun',
    'Tapanuli Selatan',
    'Tapanuli Tengah',
    'Tapanuli Utara',
    'Toba',
  ],
  'West Sumatra': [
    'Agam',
    'Dharmasraya',
    'Kepulauan Mentawai',
    'Kota Bukittinggi',
    'Kota Padang',
    'Kota Padang Panjang',
    'Kota Pariaman',
    'Kota Payakumbuh',
    'Kota Sawahlunto',
    'Kota Solok',
    'Lima Puluh Kota',
    'Padang Pariaman',
    'Pasaman',
    'Pasaman Barat',
    'Pesisir Selatan',
    'Sijunjung',
    'Solok',
    'Solok Selatan',
    'Tanah Datar',
  ],
  Riau: [
    'Bengkalis',
    'Indragiri Hilir',
    'Indragiri Hulu',
    'Kampar',
    'Kepulauan Meranti',
    'Kota Dumai',
    'Kota Pekanbaru',
    'Kuantan Singingi',
    'Pelalawan',
    'Rokan Hilir',
    'Rokan Hulu',
    'Siak',
  ],
  Jambi: [
    'Batanghari',
    'Bungo',
    'Kerinci',
    'Kota Jambi',
    'Kota Sungai Penuh',
    'Merangin',
    'Muaro Jambi',
    'Sarolangun',
    'Tanjung Jabung Barat',
    'Tanjung Jabung Timur',
    'Tebo',
  ],
  Bengkulu: [
    'Bengkulu Selatan',
    'Bengkulu Tengah',
    'Bengkulu Utara',
    'Kaur',
    'Kepahiang',
    'Kota Bengkulu',
    'Lebong',
    'Muko Muko',
    'Rejang Lebong',
    'Seluma',
  ],
  'South Sumatra': [
    'Banyuasin',
    'Empat Lawang',
    'Kota Lubuk Linggau',
    'Kota Pagar Alam',
    'Kota Palembang',
    'Kota Prabumulih',
    'Lahat',
    'Muara Enim',
    'Musi Banyuasin',
    'Musi Rawas',
    'Musi Rawas Utara',
    'Ogan Ilir',
    'Ogan Komering Ilir',
    'Ogan Komering Ulu',
    'Ogan Komering Ulu Selatan',
    'Ogan Komering Ulu Timur',
    'Penukal Abab Lematang Ilir',
  ],
  Lampung: [
    'Kota Bandar Lampung',
    'Kota Metro',
    'Lampung Barat',
    'Lampung Selatan',
    'Lampung Tengah',
    'Lampung Timur',
    'Lampung Utara',
    'Mesuji',
    'Pesawaran',
    'Pesisir Barat',
    'Pringsewu',
    'Tanggamus',
    'Tulang Bawang',
    'Tulang Bawang Barat',
    'Way Kanan',
  ],
  'Bangka Belitung Islands': [
    'Bangka',
    'Bangka Barat',
    'Bangka Selatan',
    'Bangka Tengah',
    'Belitung',
    'Belitung Timur',
    'Kota Pangkal Pinang',
  ],
  'Riau Islands': [
    'Bintan',
    'Karimun',
    'Kepulauan Anambas',
    'Kota Batam',
    'Kota Tanjung Pinang',
    'Lingga',
    'Natuna',
  ],
  Jakarta: [
    'Adm. Kep. Seribu',
    'Kota Adm. Jakarta Barat',
    'Kota Adm. Jakarta Pusat',
    'Kota Adm. Jakarta Selatan',
    'Kota Adm. Jakarta Timur',
    'Kota Adm. Jakarta Utara',
  ],
  Banten: [
    'Kota Cilegon',
    'Kota Serang',
    'Kota Tangerang',
    'Kota Tangerang Selatan',
    'Lebak',
    'Pandeglang',
    'Serang',
    'Tangerang',
  ],
  'West Java': [
    'Bandung',
    'Bandung Barat',
    'Bekasi',
    'Bogor',
    'Ciamis',
    'Cianjur',
    'Cirebon',
    'Garut',
    'Indramayu',
    'Karawang',
    'Kota Bandung',
    'Kota Banjar',
    'Kota Bekasi',
    'Kota Bogor',
    'Kota Cimahi',
    'Kota Cirebon',
    'Kota Depok',
    'Kota Sukabumi',
    'Kota Tasikmalaya',
    'Kuningan',
    'Majalengka',
    'Pangandaran',
    'Purwakarta',
    'Subang',
    'Sukabumi',
    'Sumedang',
    'Tasikmalaya',
  ],
  'Central Java': [
    'Banjarnegara',
    'Banyumas',
    'Batang',
    'Blora',
    'Boyolali',
    'Brebes',
    'Cilacap',
    'Demak',
    'Grobogan',
    'Jepara',
    'Karanganyar',
    'Kebumen',
    'Kendal',
    'Klaten',
    'Kota Magelang',
    'Kota Pekalongan',
    'Kota Salatiga',
    'Kota Semarang',
    'Kota Surakarta',
    'Kota Tegal',
    'Kudus',
    'Magelang',
    'Pati',
    'Pekalongan',
    'Pemalang',
    'Purbalingga',
    'Purworejo',
    'Rembang',
    'Semarang',
    'Sragen',
    'Sukoharjo',
    'Tegal',
    'Temanggung',
    'Wonogiri',
    'Wonosobo',
  ],
  Yogyakarta: [
    'Bantul',
    'Gunungkidul',
    'Kota Yogyakarta',
    'Kulon Progo',
    'Sleman',
  ],
  'East Java': [
    'Bangkalan',
    'Banyuwangi',
    'Blitar',
    'Bojonegoro',
    'Bondowoso',
    'Gresik',
    'Jember',
    'Jombang',
    'Kediri',
    'Kota Batu',
    'Kota Blitar',
    'Kota Kediri',
    'Kota Madiun',
    'Kota Malang',
    'Kota Mojokerto',
    'Kota Pasuruan',
    'Kota Probolinggo',
    'Kota Surabaya',
    'Lamongan',
    'Lumajang',
    'Madiun',
    'Magetan',
    'Malang',
    'Mojokerto',
    'Nganjuk',
    'Ngawi',
    'Pacitan',
    'Pamekasan',
    'Pasuruan',
    'Ponorogo',
    'Probolinggo',
    'Sampang',
    'Sidoarjo',
    'Situbondo',
    'Sumenep',
    'Trenggalek',
    'Tuban',
    'Tulungagung',
  ],
  Bali: [
    'Badung',
    'Bangli',
    'Buleleng',
    'Gianyar',
    'Jembrana',
    'Karangasem',
    'Klungkung',
    'Kota Denpasar',
    'Tabanan',
  ],
  'West Nusa Tenggara': [
    'Bima',
    'Dompu',
    'Kota Bima',
    'Kota Mataram',
    'Lombok Barat',
    'Lombok Tengah',
    'Lombok Timur',
    'Lombok Utara',
    'Sumbawa',
    'Sumbawa Barat',
  ],
  'East Nusa Tenggara': [
    'Alor',
    'Belu',
    'Ende',
    'Flores Timur',
    'Kota Kupang',
    'Kupang',
    'Lembata',
    'Malaka',
    'Manggarai',
    'Manggarai Barat',
    'Manggarai Timur',
    'Nagekeo',
    'Ngada',
    'Rote Ndao',
    'Sabu Raijua',
    'Sikka',
    'Sumba Barat',
    'Sumba Barat Daya',
    'Sumba Tengah',
    'Sumba Timur',
    'Timor Tengah Selatan',
    'Timor Tengah Utara',
  ],
  'West Kalimantan': [
    'Bengkayang',
    'Kapuas Hulu',
    'Kayong Utara',
    'Ketapang',
    'Kota Pontianak',
    'Kota Singkawang',
    'Kubu Raya',
    'Landak',
    'Melawi',
    'Mempawah',
    'Sambas',
    'Sanggau',
    'Sekadau',
    'Sintang',
  ],
  'Central Kalimantan': [
    'Barito Selatan',
    'Barito Timur',
    'Barito Utara',
    'Gunung Mas',
    'Kapuas',
    'Katingan',
    'Kota Palangkaraya',
    'Kotawaringin Barat',
    'Kotawaringin Timur',
    'Lamandau',
    'Murung Raya',
    'Pulang Pisau',
    'Seruyan',
    'Sukamara',
  ],
  'South Kalimantan': [
    'Balangan',
    'Banjar',
    'Barito Kuala',
    'Hulu Sungai Selatan',
    'Hulu Sungai Tengah',
    'Hulu Sungai Utara',
    'Kota Banjarbaru',
    'Kota Banjarmasin',
    'Kotabaru',
    'Tabalong',
    'Tanah Bumbu',
    'Tanah Laut',
    'Tapin',
  ],
  'East Kalimantan': [
    'Berau',
    'Kota Balikpapan',
    'Kota Bontang',
    'Kota Samarinda',
    'Kutai Barat',
    'Kutai Kartanegara',
    'Kutai Timur',
    'Mahakam Ulu',
    'Paser',
    'Penajam Paser Utara',
  ],
  'North Kalimantan': [
    'Bulungan',
    'Kota Tarakan',
    'Malinau',
    'Nunukan',
    'Tana Tidung',
  ],
  'North Sulawesi': [
    'Bolaang Mongondow',
    'Bolaang Mongondow Selatan',
    'Bolaang Mongondow Timur',
    'Bolaang Mongondow Utara',
    'Kep. Siau Tagulandang Biaro',
    'Kepulauan Sangihe',
    'Kepulauan Talaud',
    'Kota Bitung',
    'Kota Kotamobagu',
    'Kota Manado',
    'Kota Tomohon',
    'Minahasa',
    'Minahasa Selatan',
    'Minahasa Tenggara',
    'Minahasa Utara',
  ],
  Gorontalo: [
    'Boalemo',
    'Bone Bolango',
    'Gorontalo',
    'Gorontalo Utara',
    'Kota Gorontalo',
    'Pohuwato',
  ],
  'Central Sulawesi': [
    'Banggai',
    'Banggai Kepulauan',
    'Banggai Laut',
    'Buol',
    'Donggala',
    'Kota Palu',
    'Morowali',
    'Morowali Utara',
    'Parigi Moutong',
    'Poso',
    'Sigi',
    'Tojo Una Una',
    'Toli Toli',
  ],
  'West Sulawesi': [
    'Majene',
    'Mamasa',
    'Mamuju',
    'Mamuju Tengah',
    'Pasangkayu',
    'Polewali Mandar',
  ],
  'South Sulawesi': [
    'Bantaeng',
    'Barru',
    'Bone',
    'Bulukumba',
    'Enrekang',
    'Gowa',
    'Jeneponto',
    'Kepulauan Selayar',
    'Kota Makassar',
    'Kota Palopo',
    'Kota Parepare',
    'Luwu',
    'Luwu Timur',
    'Luwu Utara',
    'Maros',
    'Pangkajene Dan Kepulauan',
    'Pinrang',
    'Sidenreng Rappang',
    'Sinjai',
    'Soppeng',
    'Takalar',
    'Tana Toraja',
    'Toraja Utara',
    'Wajo',
  ],
  'Southeast Sulawesi': [
    'Bombana',
    'Buton',
    'Buton Selatan',
    'Buton Tengah',
    'Buton Utara',
    'Kolaka',
    'Kolaka Timur',
    'Kolaka Utara',
    'Konawe',
    'Konawe Kepulauan',
    'Konawe Selatan',
    'Konawe Utara',
    'Kota Bau Bau',
    'Kota Kendari',
    'Muna',
    'Muna Barat',
    'Wakatobi',
  ],
  Maluku: [
    'Buru',
    'Buru Selatan',
    'Kepulauan Aru',
    'Kepulauan Tanimbar',
    'Kota Ambon',
    'Kota Tual',
    'Maluku Barat Daya',
    'Maluku Tengah',
    'Maluku Tenggara',
    'Seram Bagian Barat',
    'Seram Bagian Timur',
  ],
  'North Maluku': [
    'Halmahera Barat',
    'Halmahera Selatan',
    'Halmahera Tengah',
    'Halmahera Timur',
    'Halmahera Utara',
    'Kepulauan Sula',
    'Kota Ternate',
    'Kota Tidore Kepulauan',
    'Pulau Morotai',
    'Pulau Taliabu',
  ],
  'West Papua': [
    'Fak Fak',
    'Kaimana',
    'Manokwari',
    'Manokwari Selatan',
    'Pegunungan Arfak',
    'Teluk Bintuni',
    'Teluk Wondama',
  ],
  'Southwest Papua': [
    'Kota Sorong',
    'Maybrat',
    'Raja Ampat',
    'Sorong',
    'Sorong Selatan',
    'Tambrauw',
  ],
  Papua: [
    'Biak Numfor',
    'Jayapura',
    'Keerom',
    'Kepulauan Yapen',
    'Kota Jayapura',
    'Mamberamo Raya',
    'Sarmi',
    'Supiori',
    'Waropen',
  ],
  'Highland Papua': [
    'Jayawijaya',
    'Lanny Jaya',
    'Mamberamo Tengah',
    'Nduga',
    'Pegunungan Bintang',
    'Tolikara',
    'Yahukimo',
    'Yalimo',
  ],
  'Central Papua': [
    'Deiyai',
    'Dogiyai',
    'Intan Jaya',
    'Mimika',
    'Nabire',
    'Paniai',
    'Puncak',
    'Puncak Jaya',
  ],
  'South Papua': ['Asmat', 'Boven Digoel', 'Mappi', 'Merauke'],
}

export const ID_REGENCIES = Object.entries(ID_MAP).flatMap(
  ([region, regencies]) =>
    regencies.map((regency) => ({
      id: regency,
      label: regency,
      region,
    }))
)

const ID_REGENCY_IDS = new Set(ID_REGENCIES.map((regency) => regency.id))
const COMBINED_REGENCY_IDS = ['Minahasa Selatan', 'Bolaang Mongondow Timur']

export function getIndonesiaRegencyIds(feature: unknown) {
  const regency = getFeatureProperties(feature)?.regency
  if (typeof regency !== 'string') return []
  if (regency === 'Minahasa Selatan/Bolaang Mongondow Timur')
    return COMBINED_REGENCY_IDS

  const normalizedRegency = regency.trim()
  return ID_REGENCY_IDS.has(normalizedRegency) ? [normalizedRegency] : []
}
